# version: '3.8'

services:

  app:
    build: .
    ports:
      - '9000:9000'
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres?schema=public"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: 'postgres:16.2'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5469:5432'
    volumes:
      - chat-backend_postgres_data:/var/lib/postgresql/data
      # copy the sql script to create tables
      # - ./sql/create_tables_v3.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  chat-backend_postgres_data:
